### ISSUE TITLE
Replicating an air coil

### ISSUE THREAD

**Issue by Blue-Spartan** [shredEngineer/MagnetiCalc#12]
Hello Sir,
Not an issue, but a question instead.  Is there any way to copy the loops from the Magpy package to the GUI Magnetic Calc? I tried looking at the documentation for Magpy, but I cannot get every (X,Y,Z) coordinate every loop creates. 
Below I attached a video of one loop I created (Magpy)- and in your GUI, I must specify every X,Y, and Z coordinates to form a loop like the one below, either manually or via a text file, and this becomes tedious for me since I am unable to get every coordinate to perfectly copy the loop from Magpy to MagnetiCalc.

https://user-images.githubusercontent.com/106849143/180044812-8f479451-7c30-4711-8109-15c39f359e28.mp4

**Comment by shredEngineer** [comment]
Hi,

thanks for your interest in the MagnetiCalc project! :)
I have no prior experience with Magpylib, but I did some searching.

I used the following code as an example:
    import magpylib as magpy
    src = magpy.current.Loop(current=1, diameter=1)
    magpy.show(src, backend='plotly')

The points are only generated when calling `magpy.show()`, and there is no way to access them.
So the internal function that generates these points must be called manually.

As a starting point, I looked at `magpylib._src.display.plotly.plotly_display` and found the following import: 'from magpylib._src.display.display_utility import draw_arrowed_circle`

With this information, we can generate the loop positions:
    from magpylib._src.display.display_utility import draw_arrowed_circle
    points = draw_arrowed_circle(current=1, diameter=1, arrow_size=1, vert=100)
    print(points)

BUT, this function generates the shape *as shown* in your video, i.e. *with* the stupid arrow head lines.
So these lines would have to be removed manually. I have not gone that far to do that.

HOWEVER, two much less cumbersome solutions exist if you just want to generate a loop:
- Modify the default MagnetiCalc project which *does* consist of just one loop, or …
- Use numpy to generate an arbitrary loop, like shown here: https://github.com/shredEngineer/MagnetiCalc#example-wire-export

Hope this helps. Have a great day! :)

**Comment by Blue-Spartan** [comment]
Hello, again @shredEngineer, 
Thank you, sir for the detailed information. I'm new to understanding how packages/libraries work, so I wasn't sure how to find internal functions. I'll experiment with what you sent me and get back to you!

Best,
Jaden C.

**Comment by shredEngineer** [comment]
My recommendation is to use PyCharm; a very powerful IDE! :)
There you can move the cursor over a keyword (e.g., function or package name) and press CTRL+B. Then you will be shown a list of usages or definitions of this keyword, and you will be able to navigate to the files containing the usage or definition. It's very convenient!

Best regards!
Paul

**Comment by Blue-Spartan** [comment]
I've been using Spyder (Python 3.10), which has a similar technique to viewing internal functionsPycahrm. I use PyCharm, but for other related work like GUIs, obviously not as great or large as the work you do, but relatively small (A couple of modules). 
The great thing about Spyder is the variable explorer- you can view an object's contents, and it's very handy when using the debugger. Again, thank you for the tips and tricks; I appreciate them.

https://user-images.githubusercontent.com/106849143/180259552-66bdf995-0150-4164-b71b-4ebb9b1ea170.mp4

**Comment by Blue-Spartan** [comment]
Hello sir,
I completed the coil I wanted, but I am having an issue importing the field data. I imported the API module to my python file and included the name of my HDF5 file, but I keep getting the error: "No such file or directory." I checked to see if my python file was in the same directory as the HDF5 file and specified the full path of the HDF5 file, but I cannot import the file to my python program.

Thanks,
Jaden C.

**Comment by Blue-Spartan** [comment]
Hello again,
I did want to ask another question. Would it be possible to gather the container data without opening the GUI? I'd like to extract the data I get from the coil by simply running my script to produce the coil and then exporting the field data (HDF5) without ever opening the GU between the process?

Thanks,
Jaden C.

**Comment by shredEngineer** [comment]
Hey Jaden,

> * **Edit**: I got the API to work by changing the HDF5 to open with Panoply

I'm actually not sure how exactly this is related to the problem, but I'm glad you were able to solve it! :)


> I'd like to extract the data I get from the coil by simply running my script to produce the coil and then exporting the field data (HDF5) without ever opening the GU between the process?

Ah, yes. Using MagnetiCalc from the command line is something that I have also thought about.

Let me go ahead an check if this is difficult to do. I'll report back to you in a short while! :)

Best,
Paul!

**Comment by shredEngineer** [comment]
Alright, I'm afraid the processing logic is coupled very tightly to the GUI, and it would be quite difficult to decouple that.

Sorry! 😌

PS: I've already started working on a major 2.0 release which will support command line operation. However, it will still take some time until the relase as I'm also working on my PhD which is very time consuming.

Have a great day!
