### ISSUE TITLE
Feature Request: Manual override of sampling volume

### ISSUE THREAD

**Issue by CSChisholm** [shredEngineer/MagnetiCalc#4]
It would be nice to allow the user to choose the bounds of the sampling volume rather than always creating a volume big enough to cover the coils.
This would be useful in the case of large coils where the user only needs to know the field close to the origin so that the number of points computed can be greatly reduced.

**Comment by shredEngineer** [comment]
Could you report if setting *zero or negative padding* values solves the problem for your use-case? – For me, this works well and I use it often. Sub-volumes, planes and lines (or even just the origin) can be selected like that. But, of course, they are always centered around the origin.

Another more flexible (although possibly more cumbersome) solution is to use the *constraint editor*:
* First, you use some trivial condition that is always true over your entire sampling volume, like -2 ≤ X ≤ +2, setting µ_r = 0. This disables the field calculation everywhere.
* Then, you use another condition (implicit equation) which defines your plane of interest, like X = 0, setting µ_r = 1, thus leaving only the YZ plane to be calculated. As described in the constraint editor info text, conditions with higher permeability take precedence, which is why this method works at all.

![Bildschirmfoto von 2021-12-29 23-31-16](https://user-images.githubusercontent.com/39415391/147708405-a992639d-eeda-4e92-8074-33bd619a08d2.png)

Maybe both of these options (negative padding / using constraints) should be communicated more clearly in the usage dialog and/or somewhere else?! :)

**Comment by CSChisholm** [comment]
Let me clarify: In the case that the coil is not centered on the origin, the only way to include the origin is by using positive padding but this creates a large volume since the volume always contains the coil.

The use case I have in mind here is that there are multiple coils of various shapes in different positions which are not necessarily connected to each other (they may have different currents) and we want to know the total field in some volume around the origin. With the field saving implementation of #2 we could calculate the field for each coil and then add them together later. But we need the field for each coil computed on the same grid (or at least common points if we do some cropping) and we don't want to compute the field for the entire volume of space since we only care about a small volume around the origin.

From your comment, I see a work around:

1.  We use positive padding for each coil so that a large volume of space is defined containing all coils (and the origin).
2. We set µ_r = 0 everywhere *except* the volume around the origin so that only the points we care about are calculated.

I haven't tested it yet, but I believe this method would work. I did read about the constraints and padding in the readme but it hadn't occurred to me to use it this way. I don't think the usage dialog is lacking.

On the other hand, I still think being able to manually set the sampling volume would be nice because this method could be error prone.

**Comment by shredEngineer** [comment]
Ah, now I *think* I get it. This is a use-case I really haven't thought about before.

Generally, the "bare" sampling volume (with zero padding) is the bounding box of the wire.
So when I wrote "origin" above, I meant the origin of the wire's bounding box.
If the wire is located somewhere away from the "absolute" origin, like translating a wire preset using the rotational symmetry transform with just a non-zero radius, then the sampling volume moves with the wire:

![Bildschirmfoto von 2021-12-30 00-25-16](https://user-images.githubusercontent.com/39415391/147710352-80b94135-d9e0-448d-9cbf-bf83d0a3853d.png)

We can now increase the padding until the sampling volume encompasses the "absolute" origin again (which is where we would like to evaluate the superposition of fields in a final step):

![Bildschirmfoto von 2021-12-30 00-25-09](https://user-images.githubusercontent.com/39415391/147710477-c4ed3b64-b80b-46d0-96dc-7e2c34dd48b3.png)

We can then use the constraint method described above to "trim" the portion of the sampling volume that's far away from the "absolute" origin and is thus not of interest for us:

![Bildschirmfoto von 2021-12-30 00-20-51](https://user-images.githubusercontent.com/39415391/147710225-248a3bbc-ecbe-4cd4-9bff-fe5d8f8867a9.png)

The very **good** news is that the sampling volume always comes in integer cubic-centimeter chunks, aligned to the "absolute" origin. So for a given fixed resolution, different overlapping sampling volumes are guaranteed to share the overlapping points *exactly* and unambiguously.

All in all, I hope I now understood what you're getting at. It can be done right now, although I agree it *could* also be done differently.
I see two solutions to make the sampling volume dimensions configurable more freely:
* Specify the bounding box completely using six numbers: (X0, Y0, Z0), (X1, Y1, Z1). This would be the most flexible and fine-grained option, but less easy to use.
* Specify the origin explicitly and also specify the "radius" explicitly (extent grows symmetrically by steps of two in every dimension, just like using the *padding* control). This would provide reasonable flexibility / fine-grained-ness while still being fairly easy to use.

There are probably other / better options, so let me know what you think! :)

**Comment by CSChisholm** [comment]
Personally, I like the first option of using six numbers because it gives maximum control but I would make it an option since most of the time the current default will be what is wanted.

**Comment by shredEngineer** [comment]
The functionality to override padding and instead set the sampling volume bounding box directly has been implemented in 28d43f9fa365e80a67e78d79947b947d23a443b7.
